# enable 24-bit color
set -as terminal-overrides ",xterm*:Tc"

# turn on mouse
set -g mouse on

# window and pane indexing
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-window on

# split in pwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# status bar
set -g status-position bottom
set -g status-style bg='#1a1b26',fg='#a9b1d6'

set -g status-right "#[bg=#9ece6a fg=#414868]  #[bg=#414868 fg=#a9b1d6, bold] #S "
set -g status-left ""

set -g window-status-current-format '#[bg=#414868, fg=#a9b1d6, bold] #W #[bg=#ff9e64, fg=#414868, bold] #I '
set -g window-status-format '#[bg=#414868, fg=#a9b1d6, bold] #W #[bg=#7aa2f7, fg=#414868, bold] #I '
